version: '3'

services:
  postgres:
    image: postgres:14.3
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  database-data:
